version: '3'
services:
  lauren_website:
    container_name: docker.pkg.github.com/zibby/laurens_site/laurenswebsite
    networks:
      - traefik2_default
    image: zibby/laurenswebsite
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.lauren.rule=Host(`lauren.zibbytechnology.ddns.net`)
      - traefik.http.routers.lauren.entrypoints=web,web-secure
      - traefik.http.routers.lauren.tls=true
      - traefik.http.routers.lauren.tls.certresolver=le
      - com.centurylinklabs.watchtower.enable=true
      - traefik.http.routers.lauren.middlewares=secured@file
networks:
  traefik2_default:
    external: true
