version: '3'
services:
  lauren_website:
    container_name: lauren_website
    networks:
      - traefik2_default
    image: docker.pkg.github.com/zibby/laurens_site/laurenswebsite
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.lauren.rule=Host(`lauren.zibbu.technology`,`lauren.zibbytechnology.ddns.net`)
      - traefik.http.routers.lauren.entrypoints=web,web-secure
      - traefik.http.routers.lauren.tls=true
      - traefik.http.routers.lauren.tls.certresolver=le
      - com.centurylinklabs.watchtower.enable=true
      - traefik.http.routers.lauren.middlewares=secured@file
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
networks:
  traefik2_default:
    external: true
