version: '3'
services:
  lauren_website:
    container_name: laurenswebsite
    networks:
      - traefik2_default
    image: zibby/laurenswebsite
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.lauren.rule=Host(`lauren.zibbytechnology.ddns.net`)
      - traefik.http.routers.lauren.entrypoints=web,web-secure
      - traefik.http.routers.lauren.tls=true
      - traefik.http.routers.lauren.tls.certresolver=le
      - com.centurylinklabs.watchtower.enable=true
        #- traefik.http.routers.lauren.middlewares=secured@file
        #links:
        #  - laurenphp
        #laurenphp:
        #  container_name: laurenphp
        #  networks:
        #    - traefik2_default
        #  image: php:7-fpm
        #  restart: always
        #  volumes:
        #    - ./web:/www
        #  labels:
        #    - traefik.enable=false
        #laurencode:
        #  container_name: laurencode
        #  network_mode: bridge
        #  image: codercom/code-server
        #  restart: always
        #  volumes:
        #    - /home/matt/compose/lauren:/home/coder/project
        #  command: code-server --allow-http --no-auth
        #laurencode-gatekeeper:
        #  container_name: laurencode-gatekeeper
        #  network_mode: bridge
        #  image: bitnami/keycloak-gatekeeper
        #  restart: always
        #  command:
        #    - /keycloak-proxy
        #    - --listen
        #    - 0.0.0.0:3000
        #    - --upstream-url
        #    - http://laurencode:8443
        #    - --discovery-url
        #    - https://keycloak.zibbytechnology.ddns.net/auth/realms/master/.well-known/openid-configuration
        #    - --redirection-url
        #    - https://laurencode.zibbytechnology.ddns.net
        #    - --client-id
        #    - laurenswebsite
        #    - --client-secret
        #    - 37693167-4cb4-498a-9315-b5ee911a22c5
        #  labels:
        #    - traefik.enable=true
        #    - traefik.frontend.rule=Host:laurencode.zibbytechnology.ddns.net
        #  links:
        #    - laurencode  
networks:
  traefik2_default:
    external: true
